package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"
	"time"

	"github.com/Arjun-P-J-WebomindApps/gobackend-prototype/internal/db/models"
	generated1 "github.com/Arjun-P-J-WebomindApps/gobackend-prototype/internal/graph/generated"
	"github.com/google/uuid"
)

// IPAddress is the resolver for the ipAddress field.
func (r *refreshTokenResolver) IPAddress(ctx context.Context, obj *models.RefreshToken) (*string, error) {
	panic(fmt.Errorf("not implemented: IPAddress - ipAddress"))
}

// UserAgent is the resolver for the userAgent field.
func (r *refreshTokenResolver) UserAgent(ctx context.Context, obj *models.RefreshToken) (*string, error) {
	panic(fmt.Errorf("not implemented: UserAgent - userAgent"))
}

// RevokedAt is the resolver for the revokedAt field.
func (r *refreshTokenResolver) RevokedAt(ctx context.Context, obj *models.RefreshToken) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: RevokedAt - revokedAt"))
}

// ReplacedBy is the resolver for the replacedBy field.
func (r *refreshTokenResolver) ReplacedBy(ctx context.Context, obj *models.RefreshToken) (*uuid.UUID, error) {
	panic(fmt.Errorf("not implemented: ReplacedBy - replacedBy"))
}

// DeletedAt is the resolver for the deletedAt field.
func (r *userResolver) DeletedAt(ctx context.Context, obj *models.User) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: DeletedAt - deletedAt"))
}

// ID is the resolver for the id field.
func (r *userOTPResolver) ID(ctx context.Context, obj *models.UserOtp) (uuid.UUID, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// RevokedAt is the resolver for the revokedAt field.
func (r *userSessionResolver) RevokedAt(ctx context.Context, obj *models.UserSession) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: RevokedAt - revokedAt"))
}

// RefreshToken returns generated1.RefreshTokenResolver implementation.
func (r *Resolver) RefreshToken() generated1.RefreshTokenResolver { return &refreshTokenResolver{r} }

// User returns generated1.UserResolver implementation.
func (r *Resolver) User() generated1.UserResolver { return &userResolver{r} }

// UserOTP returns generated1.UserOTPResolver implementation.
func (r *Resolver) UserOTP() generated1.UserOTPResolver { return &userOTPResolver{r} }

// UserSession returns generated1.UserSessionResolver implementation.
func (r *Resolver) UserSession() generated1.UserSessionResolver { return &userSessionResolver{r} }

type refreshTokenResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type userOTPResolver struct{ *Resolver }
type userSessionResolver struct{ *Resolver }
