// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Name      string
	Username  string
	Email     string
	Password  string
	Mobile    string
	Role      int32
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type UserOtp struct {
	ID        int32
	UserID    uuid.UUID
	OtpCode   string
	ExpiresAt time.Time
	IsUsed    bool
	CreatedAt time.Time
}

type UserSession struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	ExpiresAt time.Time
	IpAddress string
}
