// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Brand struct {
	ID   uuid.UUID
	Name string
}

type Category struct {
	ID    uuid.UUID
	Name  string
	Image sql.NullString
}

type Company struct {
	ID     uuid.UUID
	Name   string
	Status bool
}

type Model struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
	Name      string
}

type ModelVariant struct {
	ID         uuid.UUID
	ModelID    uuid.UUID
	ModelType  sql.NullString
	ModelImage sql.NullString
}

type ProductPart struct {
	ID         uuid.UUID
	CompanyID  uuid.UUID
	ModelID    uuid.UUID
	BrandID    uuid.UUID
	CategoryID uuid.UUID
	PartNo     string
	IsActive   sql.NullBool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	SessionID  uuid.UUID
	TokenHash  string
	IpAddress  sql.NullString
	UserAgent  sql.NullString
	CreatedAt  time.Time
	ExpiresAt  time.Time
	RevokedAt  sql.NullTime
	ReplacedBy uuid.NullUUID
}

type User struct {
	ID          uuid.UUID
	Name        string
	Username    string
	Email       string
	Password    string
	Mobile      string
	Role        int32
	IsActive    bool
	MaxSessions int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type UserOtp struct {
	ID        int32
	UserID    uuid.UUID
	OtpCode   string
	ExpiresAt time.Time
	IsUsed    bool
	CreatedAt time.Time
}

type UserSession struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
	IpAddress string
	UserAgent string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}
